In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

## Making an array in Numpy

Make a simple array of zeros. This returns an object of class "ndarray".

In [2]:
a = np.zeros(100, dtype=np.int32)
print(a)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


Check size (number of elements) and number of bytes per element.

In [3]:
print(a.size)
print(a.itemsize)

100
4


64-bit quantities of course take more memory per element.

In [4]:
a = np.zeros(100, dtype=np.float64)
print(a.itemsize)

8


Make an array of ones, this time with a floating point data type.

In [5]:
a = np.ones(100, dtype=np.float32)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Make an array with an increasing sequence of numbers.

In [6]:
a = np.arange(100, dtype=np.int32)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


Reference different elements of the array.

In [7]:
print(a[0])

0


In [8]:
print(a[50])

50


Reference a range of elements. Note oddity that it is a[first:last+1].

In [10]:
print(a[2:5])

[2 3 4]


Can use shortcuts to reference to end of array.

In [11]:
print(a[90:])

[90 91 92 93 94 95 96 97 98 99]


In [12]:
print(a[10:30:2])

[10 12 14 16 18 20 22 24 26 28]


Can add (or multiple, divide, etc) two arrays of the same size:

In [23]:
a = np.ones(10000000, dtype=np.float32) * 2
b = np.ones(10000000, dtype=np.float32)

In [24]:
print(a)

[2. 2. 2. ... 2. 2. 2.]


In [25]:
print(b)

[1. 1. 1. ... 1. 1. 1.]


In [26]:
print(a * b)

[2. 2. 2. ... 2. 2. 2.]


In [27]:
print(a + b)

[3. 3. 3. ... 3. 3. 3.]


In [30]:
print(b / a)

[0.5 0.5 0.5 ... 0.5 0.5 0.5]


In [29]:
c = np.zeros(10000000)
for i in np.arange(len(c)):
    c[i] = b[i] / a[i]
print(c)

[0.5 0.5 0.5 ... 0.5 0.5 0.5]


In [31]:
d = np.append(b, a)
print(d.size)

20000000


## Multidimensional arrays

We can define a multidimensional array as well. We pass NumPy a "tuple" containing the array dimensions that we want.

In [32]:
a = np.ones((12, 4), dtype=np.int32)

Note that if I print the array, the first index tells me which "row" I am looking at, and the second which "column." This is a convention choice in NumPy.

In [33]:
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


I can convert the array to a 1D array by "flattening" it:

In [34]:
aflat = a.flatten()
print(aflat)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1]


We can see below how the array is stored in memory by looking at a flattened array:

In [35]:
a[2, 3] = 2
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


This test reveals that the array is stored as the first row, then the second row, then the third, etc.

In [36]:
aflat = a.flatten()
print(aflat)

[1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1]


In [37]:
print(aflat.reshape((6,8)))

[[1 1 1 1 1 1 1 1]
 [1 1 1 2 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


A more reliable way to determine this is to ask the object about the length (in bytes) of the "stride" it takes in memory in each dimension. In this case, each row increment is 4 4-byte numbers, so 16 bytes, and each column increment is 1 4-byte number, so 4 bytes.

In [39]:
print(a.strides)

(16, 4)


Another example:

In [40]:
b = np.zeros((10, 20))
print(b.strides)

(160, 8)


In [41]:
b?

Differences between lists and arrays

In [43]:
mylist = [1., np, b, (3,4,4,), [1., 2.], np.ones]
print(mylist)

[1.0, <module 'numpy' from '/home/blanton/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>, array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0.

In [44]:
alist = [1., 1., 1., 3.]
aarray = np.ones(4)
aarray[3] = 3.
print(alist)
print(aarray)

[1.0, 1.0, 1.0, 3.0]
[1. 1. 1. 3.]


In [45]:
print(alist[2])

1.0


In [46]:
print(aarray[2])

1.0


In [47]:
print(aarray + aarray)

[2. 2. 2. 6.]


In [48]:
print(alist + alist)

[1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0]


In [49]:
print(alist + aarray)
print(aarray + alist)

[2. 2. 2. 6.]
[2. 2. 2. 6.]


In [50]:
print(np.array(alist))

[1. 1. 1. 3.]


In [51]:
blist = [1., 1., 1., "hello"]
print(blist)

[1.0, 1.0, 1.0, 'hello']


## ufuncs

ufuncs are methods of ndarray objects that act on the array as a whole. To show how ufuncs work, I will generate a set of random numbers (uniform between 0 and 1).

In [52]:
r = np.random.random(100)
print(r)

[0.1853747  0.09365845 0.51935339 0.29193526 0.99584052 0.34704142
 0.92053445 0.98578464 0.13272212 0.59948358 0.11309622 0.49387564
 0.2458312  0.96193655 0.71992168 0.3290017  0.13244162 0.55521928
 0.15762737 0.16921791 0.48830429 0.22773625 0.39543594 0.00838427
 0.83530795 0.18577718 0.99532317 0.80444398 0.30142847 0.60054818
 0.74051304 0.99839664 0.12427958 0.38950499 0.59457529 0.30970504
 0.72406134 0.78774433 0.78873474 0.50302331 0.54224596 0.11292615
 0.72726906 0.43194065 0.7803427  0.40203113 0.76405172 0.94689447
 0.02603916 0.18640268 0.16691859 0.36898642 0.3679013  0.56476644
 0.53866284 0.16766431 0.25498248 0.18517552 0.60731892 0.64985765
 0.95777217 0.28870108 0.26658837 0.68434548 0.89725875 0.27202311
 0.44695805 0.90268011 0.08956215 0.78298988 0.10919554 0.29069755
 0.6135511  0.2440932  0.71551237 0.50726806 0.92909575 0.92170009
 0.04569336 0.33018581 0.04062559 0.37016171 0.22658246 0.4064758
 0.93879413 0.7473148  0.41458074 0.99558679 0.17656078 0.84674

In [53]:
print(r.max())

0.9983966398080676


In [54]:
print(r.min())

0.008384265147582948


In [55]:
print(r.mean())

0.48957434798282873


In [56]:
print(r.std())

0.29574914912002465


In [57]:
print(1./np.sqrt(12.))

0.2886751345948129


In [58]:
print(r > 0.9)

[False False False False  True False  True  True False False False False
 False  True False False False False False False False False False False
 False False  True False False False False  True False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
  True False False False False False False  True False False False False
 False False False False  True  True False False False False False False
  True False False  True False False False False False  True False False
 False False False False]


In [59]:
print(r[r > 0.9])   # boolean

[0.99584052 0.92053445 0.98578464 0.96193655 0.99532317 0.99839664
 0.94689447 0.95777217 0.90268011 0.92909575 0.92170009 0.93879413
 0.99558679 0.90501597]


In [60]:
print((r > 0.9).sum())

14


In [61]:
print(np.sort(r))

[0.00838427 0.02603916 0.03940381 0.04062559 0.04569336 0.08956215
 0.09365845 0.10919554 0.11292615 0.11309622 0.12427958 0.13244162
 0.13272212 0.15762737 0.16691859 0.16766431 0.16921791 0.17656078
 0.18517552 0.1853747  0.18577718 0.18640268 0.22658246 0.22773625
 0.23019941 0.2440932  0.2458312  0.25498248 0.26658837 0.27202311
 0.28870108 0.29069755 0.29193526 0.29432428 0.30142847 0.30710338
 0.30927801 0.30970504 0.3290017  0.33018581 0.34704142 0.3679013
 0.36898642 0.37016171 0.38950499 0.39543594 0.40203113 0.4064758
 0.41458074 0.43194065 0.44695805 0.48830429 0.49387564 0.50302331
 0.50726806 0.51935339 0.52076336 0.53866284 0.54224596 0.55521928
 0.56476644 0.59457529 0.59948358 0.60054818 0.60731892 0.6135511
 0.64058612 0.64985765 0.68434548 0.71551237 0.71992168 0.72406134
 0.72726906 0.74051304 0.7473148  0.76405172 0.7803427  0.78298988
 0.78774433 0.78873474 0.80444398 0.82934579 0.83530795 0.8467462
 0.87660988 0.89725875 0.90268011 0.90501597 0.92053445 0.92170009

In [62]:
print(np.sort(r) > 0.9)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [63]:
isort = np.argsort(r)
print(isort)

[23 48 98 80 78 68  1 70 41 10 32 16  8 18 50 55 19 88 57  0 25 49 82 21
 95 73 12 56 62 65 61 71  3 90 28 96 91 35 15 79  5 52 51 81 33 22 45 83
 86 43 66 20 11 39 75  2 94 54 40 17 53 34  9 29 58 72 99 59 63 74 14 36
 42 30 85 46 44 69 37 38 27 92 24 89 97 64 67 93  6 77 76 84 47 60 13  7
 26 87  4 31]


In [65]:
print(r[31])

0.9983966398080676


In [67]:
print(r[isort[0:20]])

[0.00838427 0.02603916 0.03940381 0.04062559 0.04569336 0.08956215
 0.09365845 0.10919554 0.11292615 0.11309622 0.12427958 0.13244162
 0.13272212 0.15762737 0.16691859 0.16766431 0.16921791 0.17656078
 0.18517552 0.1853747 ]


In [68]:
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [69]:
b = a

In [70]:
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [71]:
b[0,0] = 2

In [72]:
print(b)

[[2 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [73]:
print(a)

[[2 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [74]:
c = a.copy()