In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

## Making an array in Numpy

Make a simple array of zeros. This returns an object of class "ndarray".

In [2]:
a = np.zeros(100, dtype=np.int32)
print(a)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


Check size (number of elements) and number of bytes per element.

In [3]:
print(a.size)
print(a.itemsize)

100
4


64-bit quantities of course take more memory per element.

In [4]:
a = np.zeros(100, dtype=np.float64)
print(a.itemsize)

8


Make an array of ones, this time with a floating point data type.

In [5]:
a = np.ones(100, dtype=np.float32)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Make an array with an increasing sequence of numbers.

In [6]:
a = np.arange(100, dtype=np.int32)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


Reference different elements of the array.

In [7]:
print(a[0])

0


In [8]:
print(a[50])

50


Reference a range of elements. Note oddity that it is a[first:last+1].

In [9]:
print(a[2:5])

[2 3 4]


Can use shortcuts to reference to end of array.

In [10]:
print(a[90:])

[90 91 92 93 94 95 96 97 98 99]


In [11]:
print(a[10:30:2])

[10 12 14 16 18 20 22 24 26 28]


Can add (or multiple, divide, etc) two arrays of the same size:

In [12]:
a = np.ones(10, dtype=np.float32) * 2
b = np.ones(10, dtype=np.float32)

In [13]:
c = np.ones((10, 10))
c[3,:]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
print(a)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [15]:
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
print(a * b)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [17]:
print(a + b)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [18]:
print(b / a)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [19]:
c = np.zeros(10)
for i in np.arange(10):
    c[i] = b[i] / a[i]
print(c)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


## Multidimensional arrays

We can define a multidimensional array as well. We pass NumPy a "tuple" containing the array dimensions that we want.

In [20]:
a = np.ones((12, 4), dtype=np.int32)

Note that if I print the array, the first index tells me which "row" I am looking at, and the second which "column." This is a convention choice in NumPy.

In [21]:
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


I can convert the array to a 1D array by "flattening" it:

In [22]:
aflat = a.flatten()
print(aflat)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1]


We can see below how the array is stored in memory by looking at a flattened array:

In [23]:
a[2, 3] = 2
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


This test reveals that the array is stored as the first row, then the second row, then the third, etc.

In [24]:
aflat = a.flatten()
print(aflat)

[1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1]


In [25]:
print(aflat.reshape((6,8)))

[[1 1 1 1 1 1 1 1]
 [1 1 1 2 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


A more reliable way to determine this is to ask the object about the length (in bytes) of the "stride" it takes in memory in each dimension. In this case, each row increment is 4 4-byte numbers, so 16 bytes, and each column increment is 1 4-byte number, so 4 bytes.

In [26]:
print(a.strides)

(16, 4)


Another example:

In [27]:
b = np.zeros((10, 20))
print(b.strides)

(160, 8)


In [28]:
b?

In [29]:
alist = [1., 1., 1., 3.]
aarray = np.ones(4)
aarray[3] = 3.
print(alist)
print(aarray)

[1.0, 1.0, 1.0, 3.0]
[1. 1. 1. 3.]


In [30]:
print(alist[2])

1.0


In [31]:
print(aarray[2])

1.0


In [32]:
print(aarray + aarray)

[2. 2. 2. 6.]


In [33]:
print(alist + alist)

[1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0]


In [34]:
print(np.array(alist))

[1. 1. 1. 3.]


In [35]:
blist = [1., 1., 1., "hello"]
print(blist)

[1.0, 1.0, 1.0, 'hello']


## ufuncs

ufuncs are methods of ndarray objects that act on the array as a whole. To show how ufuncs work, I will generate a set of random numbers (uniform between 0 and 1).

In [36]:
r = np.random.random(100)
print(r)

[0.90880323 0.70129185 0.86647627 0.78563923 0.80840353 0.80333618
 0.01527808 0.84515102 0.40442796 0.52457493 0.80638969 0.31275696
 0.50073705 0.79166613 0.44872912 0.03040537 0.15186637 0.64740624
 0.18410538 0.04258251 0.85016805 0.9384162  0.41154527 0.26456694
 0.40951446 0.33717395 0.24574644 0.37799379 0.28337823 0.18277409
 0.01844348 0.97264532 0.94039375 0.52971793 0.6493588  0.05739695
 0.6311348  0.26737369 0.53803638 0.06817863 0.97718495 0.16455843
 0.91048841 0.91193053 0.80847368 0.53425085 0.76864854 0.09888803
 0.77519636 0.0825522  0.14634113 0.61361666 0.32607163 0.4387392
 0.76901864 0.86256915 0.85007412 0.06297026 0.05014639 0.30362953
 0.64955276 0.20954158 0.80006247 0.66722794 0.21861628 0.40920793
 0.0159961  0.69246755 0.36593812 0.99300115 0.48111232 0.76752304
 0.87362638 0.77435713 0.29313196 0.11773973 0.51278003 0.16802256
 0.49661831 0.58466217 0.93898067 0.71740593 0.20591136 0.26228829
 0.20643842 0.2149364  0.18223838 0.60940101 0.67791003 0.44264

In [37]:
print(r.max())

0.9930011517965228


In [38]:
print(r.min())

0.015278076553287834


In [39]:
print(r.mean())

0.4966813997604429


In [40]:
print(r.std())

0.29583200124767706


In [41]:
print(r > 0.9)

[ True False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False  True  True False False False
 False False False False  True False  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False  True False False False
 False False False False False False False False False  True False False
 False False False False]


In [42]:
print(np.sort(r))

[0.01527808 0.0159961  0.01844348 0.03040537 0.04258251 0.05014639
 0.05732543 0.05739695 0.06297026 0.06817863 0.07018616 0.0825522
 0.09888803 0.11773973 0.14634113 0.15186637 0.16455843 0.16802256
 0.18223838 0.18277409 0.18410538 0.20591136 0.20643842 0.20954158
 0.2149364  0.21861628 0.24574644 0.26228829 0.26456694 0.26737369
 0.28337823 0.29313196 0.30362953 0.31275696 0.32607163 0.32900768
 0.33717395 0.36593812 0.37799379 0.3861167  0.40442796 0.40920793
 0.40951446 0.41154527 0.4387392  0.44264218 0.44872912 0.48111232
 0.49661831 0.50073705 0.51278003 0.52457493 0.52971793 0.53425085
 0.53803638 0.56904686 0.58466217 0.58563589 0.60940101 0.61361666
 0.63064251 0.6311348  0.64740624 0.6493588  0.64955276 0.66722794
 0.67791003 0.69246755 0.70129185 0.71740593 0.7492715  0.76752304
 0.76864854 0.76901864 0.77435713 0.77519636 0.77854676 0.78563923
 0.79166613 0.80006247 0.80333618 0.80638969 0.80840353 0.80847368
 0.84515102 0.85007412 0.85016805 0.86256915 0.86647627 0.87362

In [43]:
print(np.sort(r) > 0.9)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True  True  True  True  True  True
  True  True  True  True]
